/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ValidarExpresion.Visual;

import ValidarExpresion.Code.Operar;

/**
 *
 * @author tutaa
 */

public class VentanaPrincipalCalc extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipalCalc() {
        initComponents();
        setLocationRelativeTo(null);
    }

    // ~ MÉTODOS
    public void limpiar() {
        tfEntrada.setText("");
    }

    public void ponerTexto(String txtPoner) {
        var txtNuevo = tfEntrada.getText() + txtPoner;
        tfEntrada.setText(txtNuevo);
    }

    public String borrarTexto() {
        var txtNuevo = tfEntrada.getText();
        txtNuevo = txtNuevo.substring(0, txtNuevo.length() - 1);
        return txtNuevo;
    }

    public boolean entradaVacia() {
        var txtNuevo = tfEntrada.getText();
        if (txtNuevo.isEmpty()) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEvaluar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        tfEntrada = new javax.swing.JTextField();
        btnParCer = new javax.swing.JButton();
        btnParAbr = new javax.swing.JButton();
        btnCorAbr = new javax.swing.JButton();
        btnCorCer = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(35, 41, 70));

        jPanel2.setBackground(new java.awt.Color(249, 244, 239));
        jPanel2.setForeground(new java.awt.Color(35, 41, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 8, 38));
        jLabel1.setText("CALCULADORA");

        btnEvaluar.setBackground(new java.awt.Color(140, 120, 81));
        btnEvaluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEvaluar.setForeground(new java.awt.Color(255, 255, 254));
        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(140, 120, 81));
        btnBorrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 254));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        tfEntrada.setEditable(false);
        tfEntrada.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N

        btnParCer.setBackground(new java.awt.Color(140, 120, 81));
        btnParCer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnParCer.setForeground(new java.awt.Color(255, 255, 254));
        btnParCer.setText(")");
        btnParCer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParCerActionPerformed(evt);
            }
        });

        btnParAbr.setBackground(new java.awt.Color(140, 120, 81));
        btnParAbr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnParAbr.setForeground(new java.awt.Color(255, 255, 254));
        btnParAbr.setText("(");
        btnParAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParAbrActionPerformed(evt);
            }
        });

        btnCorAbr.setBackground(new java.awt.Color(140, 120, 81));
        btnCorAbr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCorAbr.setForeground(new java.awt.Color(255, 255, 254));
        btnCorAbr.setText("{");
        btnCorAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorAbrActionPerformed(evt);
            }
        });

        btnCorCer.setBackground(new java.awt.Color(140, 120, 81));
        btnCorCer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCorCer.setForeground(new java.awt.Color(255, 255, 254));
        btnCorCer.setText("}");
        btnCorCer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorCerActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(140, 120, 81));
        btn7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 254));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(140, 120, 81));
        btn4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 254));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(140, 120, 81));
        btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 254));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(140, 120, 81));
        btn8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 254));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(140, 120, 81));
        btn5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 254));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(140, 120, 81));
        btn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 254));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(140, 120, 81));
        btn9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 254));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(140, 120, 81));
        btn6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 254));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(140, 120, 81));
        btn3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 254));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(140, 120, 81));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 254));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(140, 120, 81));
        btn0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 254));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnMultiplicar.setBackground(new java.awt.Color(140, 120, 81));
        btnMultiplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMultiplicar.setForeground(new java.awt.Color(255, 255, 254));
        btnMultiplicar.setText("*");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnDividir.setBackground(new java.awt.Color(140, 120, 81));
        btnDividir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDividir.setForeground(new java.awt.Color(255, 255, 254));
        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnRestar.setBackground(new java.awt.Color(140, 120, 81));
        btnRestar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRestar.setForeground(new java.awt.Color(255, 255, 254));
        btnRestar.setText("-");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });

        btnSumar.setBackground(new java.awt.Color(140, 120, 81));
        btnSumar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSumar.setForeground(new java.awt.Color(255, 255, 254));
        btnSumar.setText("+");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfEntrada)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btn7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                86,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btn4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                86,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btn1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                86,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btn8,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                86,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btn5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                86,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btn2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                86,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(btn6,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                86,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(btn3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                86,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel2Layout.createSequentialGroup()
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(btn9,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                86,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(btn0,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnParAbr,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnParCer,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btnEvaluar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnCorAbr, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnMultiplicar,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(btnDividir,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnRestar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnCorCer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(12, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(126, 126, 126)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfEntrada)
                                        .addComponent(btnEvaluar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(btn7,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btn4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btn1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(btn8,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btn5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btn2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(63, 63, 63)
                                                                .addComponent(btn6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btn3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnParAbr, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnParCer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnLimpiar,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(63, 63, 63)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(btnDividir,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                45,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btnMultiplicar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                45,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(btnRestar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                45,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btnSumar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                45,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnCorCer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnCorAbr, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(16, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // & Botones de ejecución
    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {
        new Operar(tfEntrada.getText());
        tfEntrada.setText(Operar.ecuacion.get(0));
    }

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {
        if (!entradaVacia()) {
            tfEntrada.setText(borrarTexto());
        }
    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {
        limpiar();
    }

    // & Botones de operación
    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("+");
    }

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("-");
    }

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("*");
    }

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("/");
    }

    // & Botones de paréntesis
    private void btnParAbrActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("(");
    }

    private void btnParCerActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto(")");
    }

    // & Botones de corchetes
    private void btnCorAbrActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("{");
    }

    private void btnCorCerActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("}");
    }

    // & Botones de números
    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("0");
    }

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("1");
    }

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("2");
    }

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("3");
    }

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("4");
    }

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("5");
    }

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("6");
    }

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("7");
    }

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("8");
    }

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {
        ponerTexto("9");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCalc.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCalc.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCalc.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCalc.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCorAbr;
    private javax.swing.JButton btnCorCer;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnParAbr;
    private javax.swing.JButton btnParCer;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField tfEntrada;
    // End of variables declaration//GEN-END:variables
}
